// <auto-generated />
using System;
using DevelopersChallenge2.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DevelopersChallenge2.Repository.Migrations
{
    [DbContext(typeof(DevelopersChallenge2Context))]
    [Migration("20200312113615_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DevelopersChallenge2.Domain.BankList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateEnd");

                    b.Property<DateTime>("DateStart");

                    b.HasKey("Id");

                    b.ToTable("BankList");
                });

            modelBuilder.Entity("DevelopersChallenge2.Domain.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BankListId");

                    b.Property<DateTime>("DatePosted");

                    b.Property<int>("IdBankList");

                    b.Property<string>("Memo");

                    b.Property<decimal>("TransactionAmount");

                    b.Property<string>("TransactionType");

                    b.HasKey("Id");

                    b.HasIndex("BankListId");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("DevelopersChallenge2.Domain.Transaction", b =>
                {
                    b.HasOne("DevelopersChallenge2.Domain.BankList")
                        .WithMany("Transactions")
                        .HasForeignKey("BankListId");
                });
#pragma warning restore 612, 618
        }
    }
}
